# Generated by Django 2.2.5 on 2019-09-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionmodel',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BN', 'Banned'), ('DU', 'Due'), ('AD', 'Adjudecated')], default='AC', max_length=12),
        ),
    ]
