# Generated by Django 2.2.5 on 2019-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionmodel',
            name='highest_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='auctionmodel',
            name='highest_bidder',
            field=models.IntegerField(default=-1),
        ),
    ]
